name: CI

on:
  push:
  pull_request:

jobs:
  build-test-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
      # tests/requirements.txt idre install maadu, illandre skip
        run: |
          python -m pip install -U pip
          pip install -r app/requirements.txt
          if [ -f tests/requirements.txt ]; then pip install -r tests/requirements.txt; fi
          pip install pytest

      - name: Run tests
        run: pytest -q

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub (optional)
        if: ${{ secrets.DOCKERHUB_USERNAME != '' && secrets.DOCKERHUB_TOKEN != '' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: .
          # push madbekadre secrets set madi; illandre local build only
          push: ${{ secrets.DOCKERHUB_USERNAME != '' && secrets.DOCKERHUB_TOKEN != '' }}
          # If pushing, better to use username/image; if not, local tag okay
          tags: ${{ (secrets.DOCKERHUB_USERNAME != '' && secrets.DOCKERHUB_TOKEN != '')
                    && format('{0}/devops-starter:{1}', secrets.DOCKERHUB_USERNAME, github.sha)
                    || format('devops-starter:{0}', github.sha) }}
